version: '3'
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8092:8092"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27018:27017"
