version: '3'
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - spring-app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
